#!/usr/bin/env escript
-define(HOST, "http://127.0.0.1:8081/dbop/").

main(_Args) ->
    ibrowse:start(),
    String = lists:concat([?HOST,
			   lb]),
    {Code, Msg} = handle_result(ibrowse:send_req(String, [], get, [])),
    io:format("return code:~p~n", [Code]),
    io:format("return message:~p~n", [Msg]).
handle_result({error, ErrorInfo}) ->
    io:format("error info:~p~n", [ErrorInfo]);

handle_result({ok, _, _, Body}) ->
    {struct, [Code1, Msg1]} = mochijson2:decode(Body),
    {<<"code">>, Code} = Code1,
    {<<"msg">> , Msg}  = Msg1,
    {Code, Msg}.
